language: dart
dart:
# Install the latest stable release
- stable
dart_task:
- test: string
  dartanalyzer: string
  dartfmt: true
before_script:
  - gem install coveralls-lcov
after_success:
  - coveralls-lcov coverage/lcov.info
cache:
  directories:
    - $HOME/.pub-cache